name: Email Scheduler

on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:

jobs:
  run-scheduler:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt

      - name: Decode GOOGLE_JSON secret
        run: |
          echo "$GOOGLE_JSON" > credentials.json

      - name: Run main.py
        env:
          GOOGLE_JSON: ${{ secrets.GOOGLE_JSON }}
        run: python main.py
